archivist:
  - archivist1
  - archivist2
  - leland_himself
admin_policy_object_editor:
  - archivist1
donor:
  - donor1
  - leland_himself
researcher:
  - researcher1
patron:
  - patron1
  - leland_himself
